name: Stylelint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "**/*.css"
      - "**/*.scss"
      - ".stylelintrc.js"
      - "package.json"
      - ".github/workflows/stylelint.yml"

jobs:
  lint:
    name: Run Stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        run: npx stylelint "wp-content/plugins/hello-world-plugin/**/*.css"

      - name: Upload Stylelint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: stylelint-results
          path: stylelint-results.json
