name: PHP Coding Standards

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: composer

      - name: Configure Composer Allow Plugins
        run: |
          composer config --global allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install Dependencies
        run: |
          composer global require squizlabs/php_codesniffer
          composer global require phpcsstandards/phpcsutils
          composer global require phpcsstandards/phpcsextra
          composer global require wp-coding-standards/wpcs

      - name: Set PHPCS WordPress Configuration
        run: |
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcsstandards/phpcsutils,$HOME/.composer/vendor/phpcsstandards/phpcsextra

      - name: Check Coding Standards
        run: phpcs
